source=~/.config/hypr/configs/animations.conf
source=~/.config/hypr/configs/decoration.conf
source=~/.config/hypr/configs/env.conf
source=~/.config/hypr/configs/general.conf
source=~/.config/hypr/configs/gestures.conf
source=~/.config/hypr/configs/input.conf
source=~/.config/hypr/configs/keybinds.conf
source=~/.config/hypr/configs/layouts.conf
source=~/.config/hypr/configs/misc.conf
source=~/.config/hypr/configs/monitors.conf
source=~/.config/hypr/configs/render.conf
source=~/.config/hypr/configs/startup.conf
source=~/.config/hypr/configs/windowrules.conf
source=~/.config/hypr/configs/workspace.conf
source=~/.config/hypr/configs/xwayland.conf