misc {
  disable_hyprland_logo = true
  background_color = rgb(000000)
  disable_splash_rendering = true
  vfr = true
  #vrr = 0
  focus_on_activate = true # focus app if it requires to be focused
  initial_workspace_tracking = 0
  middle_click_paste = false
  disable_autoreload = false # run hyprctl reload to relaod config
}