monitor = desc:Philips Consumer Electronics Company 32M2N6800M AU82441000588, 3840x2160@120.01Hz, 0x0, 1.333333, bitdepth, 10, cm, hdr, sdrbrightness, 1.4, sdrsaturation, 1.2
monitor = desc:Dell Inc. DELL P2723QE 8K3JT04, preferred, 2883x-760, auto, transform, 1

# monitorv2 {
#     name = desc:Philips Consumer Electronics Company 32M2N6800M AU82441000588
#     mode = 3840x2160@120.01Hz
#     position = 0x0
#     scale = 1.333333
#     bitdepth = 10
#     cm = hdr
#     sdrbrightness = 1.4
#     sdrsaturation = 1.2
#     sdr_min_luminance = 0.005
# }

# monitorv2 {
#     name =  desc:Dell Inc. DELL P2723QE 8K3JT04
#     mode = preferred
#     position = 2880x0
#     scale = auto
#     transform = 1 # vertical
# }