# exec-once = if [ "$XDG_CURRENT_DESKTOP" = "Hyprland" ]; then systemctl --user start hyprpolkitagent.service; fi
exec-once = if [ "$XDG_CURRENT_DESKTOP" = "Hyprland" ]; then systemctl --user start waybar.service; fi
exec-once = if [ "$XDG_CURRENT_DESKTOP" = "Hyprland" ]; then systemctl --user start darkman.service; fi
exec-once = if [ "$XDG_CURRENT_DESKTOP" = "Hyprland" ]; then systemctl --user start hyprsunset.service; fi

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP # for XDPH
exec-once = dbus-update-activation-environment --systemd --all # for XDPH
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP # for XDPH
exec-once = uwsm app -- ~/.config/hypr/kill_desktop_portals.sh
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = uwsm app -- nm-applet --indicator & # network manager tray
exec-once = uwsm app -- blueman-applet
exec-once = uwsm app -- dunst
exec-once = uwsm app -- wl-paste --type text --watch cliphist store
exec-once = uwsm app -- wl-paste --type image --watch cliphist store
exec = uwsm app -- eww daemon
exec-once = uwsm app -- ~/.config/eww/scripts/start.sh
exec-once = uwsm app -- swww-daemon
exec-once = swww img ~/Pictures/Wallpapers/1.png
exec = hyprctl setcursor Gruv-Cursor 30
exec = gsettings set org.gnome.desktop.interface cursor-theme 'Gruv-Cursor'
exec = gsettings set org.gnome.desktop.interface cursor-size 25
exec = gsettings set org.gnome.desktop.interface font-name 'SF Pro Display Regular 10'
exec = gsettings set org.gnome.desktop.interface document-font-name 'SF Pro Display Regular 10'
exec = gsettings set org.gnome.desktop.interface monospace-font-name 'CaskaydiaCove Nerd Font Mono 9'
exec = gsettings set org.gnome.desktop.interface font-antialiasing 'rgba'
exec = gsettings set org.gnome.desktop.interface font-hinting 'full'

exec-once = [workspace 9 silent] uwsm app -- steam-native
exec-once = [workspace 9 silent] uwsm app -- equibop