workspace = 1, monitor:desc:Philips Consumer Electronics Company 32M2N6800M AU82441000588, default:true,persistent:true
workspace = 2, monitor:desc:Philips Consumer Electronics Company 32M2N6800M AU82441000588
workspace = 3, monitor:desc:Philips Consumer Electronics Company 32M2N6800M AU82441000588
workspace = 4, monitor:desc:Philips Consumer Electronics Company 32M2N6800M AU82441000588
workspace = 5, monitor:desc:Dell Inc. DELL P2723QE 8K3JT04,default:true
workspace = 6, monitor:desc:Dell Inc. DELL P2723QE 8K3JT04
workspace = 7, monitor:desc:Dell Inc. DELL P2723QE 8K3JT04
workspace = 8, monitor:desc:Dell Inc. DELL P2723QE 8K3JT04
workspace = 9, monitor:desc:Dell Inc. DELL P2723QE 8K3JT04